/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/worker-configuration.d.ts --include-runtime false --env-file .empty.env` (hash: 643b49ba86ae1ef35879c7cfd05d6ce3)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "ConfigDurableObject";
	}
	interface StagingEnv {
		FP_CONFIGS: R2Bucket;
		FP_DB: D1Database;
		FP_ANALYTICS: AnalyticsEngineDataset;
		FP_EVENTS: Queue;
		ENVIRONMENT: "staging";
		API_SECRET: string;
		CLAIM_SECRET: string;
		SEED_ADMIN_EMAIL: string;
		SEED_ADMIN_PASSWORD: string;
		SEED_TENANT_USER_EMAIL: string;
		SEED_TENANT_USER_PASSWORD: string;
		CONFIG_DO: DurableObjectNamespace<import("./index").ConfigDurableObject>;
	}
	interface DevEnv {
		FP_CONFIGS: R2Bucket;
		FP_DB: D1Database;
		FP_ANALYTICS: AnalyticsEngineDataset;
		FP_EVENTS: Queue;
		ENVIRONMENT: "dev";
		API_SECRET: string;
		CLAIM_SECRET: string;
		SEED_ADMIN_EMAIL: string;
		SEED_ADMIN_PASSWORD: string;
		SEED_TENANT_USER_EMAIL: string;
		SEED_TENANT_USER_PASSWORD: string;
		CONFIG_DO: DurableObjectNamespace<import("./index").ConfigDurableObject>;
	}
	interface ProductionEnv {
		FP_CONFIGS: R2Bucket;
		FP_DB: D1Database;
		FP_ANALYTICS: AnalyticsEngineDataset;
		FP_EVENTS: Queue;
		ENVIRONMENT: "production";
		API_SECRET: string;
		CLAIM_SECRET: string;
		SEED_ADMIN_EMAIL: string;
		SEED_ADMIN_PASSWORD: string;
		SEED_TENANT_USER_EMAIL: string;
		SEED_TENANT_USER_PASSWORD: string;
		CONFIG_DO: DurableObjectNamespace<import("./index").ConfigDurableObject>;
	}
	interface Env {
		FP_CONFIGS: R2Bucket;
		FP_DB: D1Database;
		FP_ANALYTICS?: AnalyticsEngineDataset;
		FP_EVENTS: Queue;
		ENVIRONMENT?: "staging" | "dev" | "production";
		API_SECRET: string;
		CLAIM_SECRET: string;
		SEED_ADMIN_EMAIL: string;
		SEED_ADMIN_PASSWORD: string;
		SEED_TENANT_USER_EMAIL: string;
		SEED_TENANT_USER_PASSWORD: string;
		CONFIG_DO: DurableObjectNamespace<import("./index").ConfigDurableObject>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "API_SECRET" | "CLAIM_SECRET" | "SEED_ADMIN_EMAIL" | "SEED_ADMIN_PASSWORD" | "SEED_TENANT_USER_EMAIL" | "SEED_TENANT_USER_PASSWORD">> {}
}
