/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/worker-configuration.d.ts --include-runtime false --env-file /dev/null` (hash: 288ec3de4ed8cb649cc0acae378986c0)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "ConfigDurableObject";
	}
	interface StagingEnv {
		FP_CONFIGS: R2Bucket;
		FP_DB: D1Database;
		FP_ANALYTICS: AnalyticsEngineDataset;
		FP_EVENTS: Queue;
		ENVIRONMENT: "staging";
		CONFIG_DO: DurableObjectNamespace<import("./index").ConfigDurableObject>;
	}
	interface ProductionEnv {
		FP_CONFIGS: R2Bucket;
		FP_DB: D1Database;
		FP_ANALYTICS: AnalyticsEngineDataset;
		FP_EVENTS: Queue;
		ENVIRONMENT: "production";
		CONFIG_DO: DurableObjectNamespace<import("./index").ConfigDurableObject>;
	}
	interface Env {
		FP_CONFIGS: R2Bucket;
		FP_DB: D1Database;
		FP_ANALYTICS?: AnalyticsEngineDataset;
		FP_EVENTS: Queue;
		ENVIRONMENT?: "staging" | "production";
		CONFIG_DO: DurableObjectNamespace<import("./index").ConfigDurableObject>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT">> {}
}
