// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnyValue {
    #[prost(oneof = "any_value::Value", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub value: ::core::option::Option<any_value::Value>,
}
/// Nested message and enum types in `AnyValue`.
pub mod any_value {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(string, tag = "1")]
        StringValue(::prost::alloc::string::String),
        #[prost(bool, tag = "2")]
        BoolValue(bool),
        #[prost(int64, tag = "3")]
        IntValue(i64),
        #[prost(double, tag = "4")]
        DoubleValue(f64),
        #[prost(message, tag = "5")]
        ArrayValue(super::ArrayValue),
        #[prost(message, tag = "6")]
        KvlistValue(super::KeyValueList),
        #[prost(bytes, tag = "7")]
        BytesValue(::prost::alloc::vec::Vec<u8>),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ArrayValue {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<AnyValue>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyValueList {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<KeyValue>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyValue {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub value: ::core::option::Option<AnyValue>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentToServer {
    #[prost(bytes = "vec", tag = "1")]
    pub instance_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub sequence_num: u64,
    #[prost(message, optional, tag = "3")]
    pub agent_description: ::core::option::Option<AgentDescription>,
    #[prost(uint64, tag = "4")]
    pub capabilities: u64,
    #[prost(message, optional, tag = "5")]
    pub health: ::core::option::Option<ComponentHealth>,
    #[prost(message, optional, tag = "6")]
    pub effective_config: ::core::option::Option<EffectiveConfig>,
    #[prost(message, optional, tag = "7")]
    pub remote_config_status: ::core::option::Option<RemoteConfigStatus>,
    /// field 8: PackageStatuses (not implemented)
    #[prost(message, optional, tag = "9")]
    pub agent_disconnect: ::core::option::Option<AgentDisconnect>,
    #[prost(uint64, tag = "10")]
    pub flags: u64,
    /// field 11: ConnectionSettingsRequest (not implemented)
    /// field 12: CustomCapabilities (not implemented)
    /// field 13: CustomMessage (not implemented)
    #[prost(message, optional, tag = "14")]
    pub available_components: ::core::option::Option<AvailableComponents>,
    /// ConnectionSettingsStatus is decoded by the codec but not yet processed by
    /// the worker — the server currently ignores the agent's acknowledgement of
    /// connection settings offers. See apps/worker TODO for tracking.
    #[prost(message, optional, tag = "15")]
    pub connection_settings_status: ::core::option::Option<ConnectionSettingsStatus>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerToAgent {
    #[prost(bytes = "vec", tag = "1")]
    pub instance_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub error_response: ::core::option::Option<ServerErrorResponse>,
    #[prost(message, optional, tag = "3")]
    pub remote_config: ::core::option::Option<AgentRemoteConfig>,
    #[prost(message, optional, tag = "4")]
    pub connection_settings: ::core::option::Option<ConnectionSettingsOffers>,
    /// field 5: PackagesAvailable (not implemented)
    #[prost(uint64, tag = "6")]
    pub flags: u64,
    #[prost(uint64, tag = "7")]
    pub capabilities: u64,
    #[prost(message, optional, tag = "8")]
    pub agent_identification: ::core::option::Option<AgentIdentification>,
    #[prost(message, optional, tag = "9")]
    pub command: ::core::option::Option<ServerToAgentCommand>,
    /// field 10: CustomCapabilities (not implemented)
    /// field 11: CustomMessage (not implemented)
    #[prost(uint64, tag = "12")]
    pub heart_beat_interval: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentDescription {
    #[prost(message, repeated, tag = "1")]
    pub identifying_attributes: ::prost::alloc::vec::Vec<KeyValue>,
    #[prost(message, repeated, tag = "2")]
    pub non_identifying_attributes: ::prost::alloc::vec::Vec<KeyValue>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ComponentHealth {
    #[prost(bool, tag = "1")]
    pub healthy: bool,
    #[prost(fixed64, tag = "2")]
    pub start_time_unix_nano: u64,
    #[prost(string, tag = "3")]
    pub last_error: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub status: ::prost::alloc::string::String,
    #[prost(fixed64, tag = "5")]
    pub status_time_unix_nano: u64,
    #[prost(map = "string, message", tag = "6")]
    pub component_health_map: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ComponentHealth,
    >,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EffectiveConfig {
    #[prost(message, optional, tag = "1")]
    pub config_map: ::core::option::Option<AgentConfigMap>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentConfigMap {
    #[prost(map = "string, message", tag = "1")]
    pub config_map: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        AgentConfigFile,
    >,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentConfigFile {
    #[prost(bytes = "vec", tag = "1")]
    pub body: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub content_type: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoteConfigStatus {
    #[prost(bytes = "vec", tag = "1")]
    pub last_remote_config_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "RemoteConfigStatuses", tag = "2")]
    pub status: i32,
    #[prost(string, tag = "3")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentRemoteConfig {
    #[prost(message, optional, tag = "1")]
    pub config: ::core::option::Option<AgentConfigMap>,
    #[prost(bytes = "vec", tag = "2")]
    pub config_hash: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServerErrorResponse {
    #[prost(enumeration = "ServerErrorResponseType", tag = "1")]
    pub r#type: i32,
    #[prost(string, tag = "2")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub retry_info: ::core::option::Option<RetryInfo>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RetryInfo {
    #[prost(uint64, tag = "1")]
    pub retry_after_nanoseconds: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentIdentification {
    #[prost(bytes = "vec", tag = "1")]
    pub new_instance_uid: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentDisconnect {}
/// Inventory of components an agent has compiled in (receivers/processors/
/// exporters/extensions/connectors). Used by the server to validate that
/// a config push only references components the agent supports. Spec status
/// is "Development" — wire-compatible with otelcol-contrib's OpAMP impl.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AvailableComponents {
    /// Field numbers match upstream opamp-spec for wire compatibility with
    /// otelcol-contrib: `components` is field 1, `hash` is field 2.
    #[prost(map = "string, message", tag = "1")]
    pub components: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ComponentDetails,
    >,
    #[prost(bytes = "vec", tag = "2")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ComponentDetails {
    #[prost(message, repeated, tag = "1")]
    pub metadata: ::prost::alloc::vec::Vec<KeyValue>,
    #[prost(map = "string, message", tag = "2")]
    pub sub_component_map: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ComponentDetails,
    >,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConnectionSettingsOffers {
    #[prost(bytes = "vec", tag = "1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub opamp: ::core::option::Option<OpAmpConnectionSettings>,
    #[prost(message, optional, tag = "3")]
    pub own_metrics: ::core::option::Option<TelemetryConnectionSettings>,
    #[prost(message, optional, tag = "4")]
    pub own_traces: ::core::option::Option<TelemetryConnectionSettings>,
    /// field 6: other_connections (not implemented)
    #[prost(message, optional, tag = "5")]
    pub own_logs: ::core::option::Option<TelemetryConnectionSettings>,
}
/// Settings for collector self-telemetry (metrics/traces/logs) export.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TelemetryConnectionSettings {
    #[prost(string, tag = "1")]
    pub destination_endpoint: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub headers: ::core::option::Option<Headers>,
    /// field 3: certificate (TLSCertificate, not implemented)
    #[prost(uint64, tag = "4")]
    pub heartbeat_interval_seconds: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpAmpConnectionSettings {
    #[prost(string, tag = "1")]
    pub destination_endpoint: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub headers: ::core::option::Option<Headers>,
    /// field 3: certificate (TLSCertificate, not implemented)
    #[prost(uint64, tag = "4")]
    pub heartbeat_interval_seconds: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Headers {
    #[prost(message, repeated, tag = "1")]
    pub headers: ::prost::alloc::vec::Vec<Header>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Header {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServerToAgentCommand {
    #[prost(enumeration = "CommandType", tag = "1")]
    pub r#type: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConnectionSettingsStatus {
    #[prost(bytes = "vec", tag = "1")]
    pub last_connection_settings_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "ConnectionSettingsStatuses", tag = "2")]
    pub status: i32,
    #[prost(string, tag = "3")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RemoteConfigStatuses {
    Unset = 0,
    Applied = 1,
    Applying = 2,
    Failed = 3,
}
impl RemoteConfigStatuses {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unset => "RemoteConfigStatuses_UNSET",
            Self::Applied => "RemoteConfigStatuses_APPLIED",
            Self::Applying => "RemoteConfigStatuses_APPLYING",
            Self::Failed => "RemoteConfigStatuses_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RemoteConfigStatuses_UNSET" => Some(Self::Unset),
            "RemoteConfigStatuses_APPLIED" => Some(Self::Applied),
            "RemoteConfigStatuses_APPLYING" => Some(Self::Applying),
            "RemoteConfigStatuses_FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ServerErrorResponseType {
    Unknown = 0,
    BadRequest = 1,
    Unavailable = 2,
}
impl ServerErrorResponseType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "ServerErrorResponseType_Unknown",
            Self::BadRequest => "ServerErrorResponseType_BadRequest",
            Self::Unavailable => "ServerErrorResponseType_Unavailable",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ServerErrorResponseType_Unknown" => Some(Self::Unknown),
            "ServerErrorResponseType_BadRequest" => Some(Self::BadRequest),
            "ServerErrorResponseType_Unavailable" => Some(Self::Unavailable),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CommandType {
    Restart = 0,
}
impl CommandType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Restart => "CommandType_Restart",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CommandType_Restart" => Some(Self::Restart),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ConnectionSettingsStatuses {
    Unset = 0,
    Applied = 1,
    Applying = 2,
    Failed = 3,
}
impl ConnectionSettingsStatuses {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unset => "ConnectionSettingsStatuses_UNSET",
            Self::Applied => "ConnectionSettingsStatuses_APPLIED",
            Self::Applying => "ConnectionSettingsStatuses_APPLYING",
            Self::Failed => "ConnectionSettingsStatuses_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ConnectionSettingsStatuses_UNSET" => Some(Self::Unset),
            "ConnectionSettingsStatuses_APPLIED" => Some(Self::Applied),
            "ConnectionSettingsStatuses_APPLYING" => Some(Self::Applying),
            "ConnectionSettingsStatuses_FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ServerCapabilities {
    Unspecified = 0,
    AcceptsStatus = 1,
    OffersRemoteConfig = 2,
    AcceptsEffectiveConfig = 4,
    /// 0x00000008 = OffersPackages (not implemented)
    /// 0x00000010 = AcceptsPackagesStatus (not implemented)
    ///
    /// 0x00000040 = AcceptsConnectionSettingsRequest (not implemented)
    OffersConnectionSettings = 32,
}
impl ServerCapabilities {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ServerCapabilities_Unspecified",
            Self::AcceptsStatus => "ServerCapabilities_AcceptsStatus",
            Self::OffersRemoteConfig => "ServerCapabilities_OffersRemoteConfig",
            Self::AcceptsEffectiveConfig => "ServerCapabilities_AcceptsEffectiveConfig",
            Self::OffersConnectionSettings => {
                "ServerCapabilities_OffersConnectionSettings"
            }
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ServerCapabilities_Unspecified" => Some(Self::Unspecified),
            "ServerCapabilities_AcceptsStatus" => Some(Self::AcceptsStatus),
            "ServerCapabilities_OffersRemoteConfig" => Some(Self::OffersRemoteConfig),
            "ServerCapabilities_AcceptsEffectiveConfig" => {
                Some(Self::AcceptsEffectiveConfig)
            }
            "ServerCapabilities_OffersConnectionSettings" => {
                Some(Self::OffersConnectionSettings)
            }
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ServerToAgentFlags {
    Unspecified = 0,
    ReportFullState = 1,
}
impl ServerToAgentFlags {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ServerToAgentFlags_Unspecified",
            Self::ReportFullState => "ServerToAgentFlags_ReportFullState",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ServerToAgentFlags_Unspecified" => Some(Self::Unspecified),
            "ServerToAgentFlags_ReportFullState" => Some(Self::ReportFullState),
            _ => None,
        }
    }
}
