// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnyValue {
    #[prost(oneof = "any_value::Value", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub value: ::core::option::Option<any_value::Value>,
}
/// Nested message and enum types in `AnyValue`.
pub mod any_value {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(string, tag = "1")]
        StringValue(::prost::alloc::string::String),
        #[prost(bool, tag = "2")]
        BoolValue(bool),
        #[prost(int64, tag = "3")]
        IntValue(i64),
        #[prost(double, tag = "4")]
        DoubleValue(f64),
        #[prost(message, tag = "5")]
        ArrayValue(super::ArrayValue),
        #[prost(message, tag = "6")]
        KvlistValue(super::KeyValueList),
        #[prost(bytes, tag = "7")]
        BytesValue(::prost::alloc::vec::Vec<u8>),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ArrayValue {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<AnyValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyValueList {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<KeyValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyValue {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub value: ::core::option::Option<AnyValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentToServer {
    #[prost(bytes = "vec", tag = "1")]
    pub instance_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub sequence_num: u64,
    #[prost(message, optional, tag = "3")]
    pub agent_description: ::core::option::Option<AgentDescription>,
    #[prost(uint64, tag = "4")]
    pub capabilities: u64,
    #[prost(message, optional, tag = "5")]
    pub health: ::core::option::Option<ComponentHealth>,
    #[prost(message, optional, tag = "6")]
    pub effective_config: ::core::option::Option<EffectiveConfig>,
    #[prost(message, optional, tag = "7")]
    pub remote_config_status: ::core::option::Option<RemoteConfigStatus>,
    /// field 8: PackageStatuses (not implemented)
    #[prost(message, optional, tag = "9")]
    pub agent_disconnect: ::core::option::Option<AgentDisconnect>,
    /// fields 11-15: Development features (not implemented)
    #[prost(uint64, tag = "10")]
    pub flags: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerToAgent {
    #[prost(bytes = "vec", tag = "1")]
    pub instance_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub error_response: ::core::option::Option<ServerErrorResponse>,
    #[prost(message, optional, tag = "3")]
    pub remote_config: ::core::option::Option<AgentRemoteConfig>,
    #[prost(message, optional, tag = "4")]
    pub connection_settings: ::core::option::Option<ConnectionSettingsOffers>,
    /// field 5: PackagesAvailable (not implemented)
    #[prost(uint64, tag = "6")]
    pub flags: u64,
    #[prost(uint64, tag = "7")]
    pub capabilities: u64,
    #[prost(message, optional, tag = "8")]
    pub agent_identification: ::core::option::Option<AgentIdentification>,
    /// fields 9-11: Beta/Development features (not implemented)
    /// Recommended minimum interval in nanoseconds between AgentToServer messages.
    #[prost(uint64, tag = "12")]
    pub heart_beat_interval: u64,
    // TODO: Rust bindings are stale — field 14 (available_components) is defined in the
    // proto but missing here. Re-run prost-build to regenerate when the Rust worker is
    // actively developed.
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentDescription {
    #[prost(message, repeated, tag = "1")]
    pub identifying_attributes: ::prost::alloc::vec::Vec<KeyValue>,
    #[prost(message, repeated, tag = "2")]
    pub non_identifying_attributes: ::prost::alloc::vec::Vec<KeyValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ComponentHealth {
    #[prost(bool, tag = "1")]
    pub healthy: bool,
    #[prost(fixed64, tag = "2")]
    pub start_time_unix_nano: u64,
    #[prost(string, tag = "3")]
    pub last_error: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub status: ::prost::alloc::string::String,
    #[prost(fixed64, tag = "5")]
    pub status_time_unix_nano: u64,
    #[prost(map = "string, message", tag = "6")]
    pub component_health_map: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ComponentHealth,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EffectiveConfig {
    #[prost(message, optional, tag = "1")]
    pub config_map: ::core::option::Option<AgentConfigMap>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentConfigMap {
    #[prost(map = "string, message", tag = "1")]
    pub config_map: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        AgentConfigFile,
    >,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentConfigFile {
    #[prost(bytes = "vec", tag = "1")]
    pub body: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub content_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoteConfigStatus {
    #[prost(bytes = "vec", tag = "1")]
    pub last_remote_config_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "RemoteConfigStatuses", tag = "2")]
    pub status: i32,
    #[prost(string, tag = "3")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentRemoteConfig {
    #[prost(message, optional, tag = "1")]
    pub config: ::core::option::Option<AgentConfigMap>,
    #[prost(bytes = "vec", tag = "2")]
    pub config_hash: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServerErrorResponse {
    #[prost(enumeration = "ServerErrorResponseType", tag = "1")]
    pub r#type: i32,
    #[prost(string, tag = "2")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub retry_info: ::core::option::Option<RetryInfo>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RetryInfo {
    #[prost(uint64, tag = "1")]
    pub retry_after_nanoseconds: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentIdentification {
    #[prost(bytes = "vec", tag = "1")]
    pub new_instance_uid: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentDisconnect {}
/// OpAMP Connection Settings for enrollment (Registration On First Use)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConnectionSettingsOffers {
    #[prost(bytes = "vec", tag = "1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub opamp: ::core::option::Option<OpAmpConnectionSettings>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpAmpConnectionSettings {
    #[prost(string, tag = "1")]
    pub destination_endpoint: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub headers: ::core::option::Option<Headers>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Headers {
    #[prost(message, repeated, tag = "1")]
    pub headers: ::prost::alloc::vec::Vec<Header>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Header {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RemoteConfigStatuses {
    Unset = 0,
    Applied = 1,
    Applying = 2,
    Failed = 3,
}
impl RemoteConfigStatuses {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unset => "RemoteConfigStatuses_UNSET",
            Self::Applied => "RemoteConfigStatuses_APPLIED",
            Self::Applying => "RemoteConfigStatuses_APPLYING",
            Self::Failed => "RemoteConfigStatuses_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RemoteConfigStatuses_UNSET" => Some(Self::Unset),
            "RemoteConfigStatuses_APPLIED" => Some(Self::Applied),
            "RemoteConfigStatuses_APPLYING" => Some(Self::Applying),
            "RemoteConfigStatuses_FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ServerErrorResponseType {
    Unknown = 0,
    BadRequest = 1,
    Unavailable = 2,
}
impl ServerErrorResponseType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "ServerErrorResponseType_Unknown",
            Self::BadRequest => "ServerErrorResponseType_BadRequest",
            Self::Unavailable => "ServerErrorResponseType_Unavailable",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ServerErrorResponseType_Unknown" => Some(Self::Unknown),
            "ServerErrorResponseType_BadRequest" => Some(Self::BadRequest),
            "ServerErrorResponseType_Unavailable" => Some(Self::Unavailable),
            _ => None,
        }
    }
}
